### ISSUE TITLE
Expression Kind is not matching

### ISSUE THREAD

**Issue by avin-kavish** [Hookyns/tst-expression#9]
Hey, thanks for the great library, was waiting for the day I could use expressions and reflection in TS :)

I've run into a small issue here. I've passed a lambda to this function, but the kind is detected as `TypeOfExpression`. It seems that's not the only one, other `kind` enum labels aren't matching up to the numbers also. I'm on typescript 4.7, I noticed your package.json is on typescript 4.4, could that be why?

```ts
function checkExpression(op: Expression<(a: Human) => boolean>) {
  assertExpression(op)
  console.log(ExpressionKind[op.expression.kind])  // <-- prints TypeOfExpression
  // assertArrowFunctionExpression(op.expression) <-- this throws.

  const expr = op.expression as ArrowFunctionExpressionNode
  const templ = expr.body as any

  console.dir(expr, { depth: 10 })
  console.log(ExpressionKind[templ.left.kind])   // <-- prints NewExpression. expected IndexedAccess
}

checkExpression(a => a['firstName'] === 'test')
```

**Comment by Hookyns** [comment]
Hi, thanks.

Yes, that was caused by TypeScript version. I've made some changes which make it more TS version independent.
Here is a StackBlitz [demo](https://stackblitz.com/edit/tst-expression-demo?file=index.ts).

Try new versions: `tst-expression-transformer@1.2.1` & `tst-expression@2.1.2`.

**Comment by avin-kavish** [comment]
thanks, it's working!
